In [1]:
import numpy as np

In [2]:
n = 64
f = 128
nnz = 256

In [3]:
dense = np.random.rand(n,f)
value = np.random.rand(nnz)
index = np.random.randint(0, n - 1, size=nnz)
indptr = np.zeros(n+1)

start=0

for i in range(n):
    incremental = np.random.randint(1,6);
    start = start + incremental
    if (start < nnz):
        indptr[i + 1] = start
    else:
        indptr[i + 1] = nnz

indptr[n] = nnz

In [4]:
len(index)

256

## this is a function for converting the float32 to IEEE 754 binary format

In [5]:
import struct
def float32toIEEE754(f):
    s = struct.pack('f', f)
    t=s.hex()
    news=''
    news=t[6]+t[7]+t[4]+t[5]+t[2]+t[3]+t[1]+t[0];
    return news

In [6]:
float32toIEEE754(1.2717441261e+20)

'60dc9c9c'

In [7]:
float32toIEEE754(1)

'3f800000'

In [8]:
indptr

array([  0.,   4.,   5.,  10.,  15.,  16.,  17.,  19.,  22.,  27.,  29.,
        31.,  35.,  40.,  43.,  48.,  52.,  55.,  60.,  65.,  68.,  72.,
        75.,  76.,  80.,  81.,  85.,  86.,  90.,  93.,  95., 100., 105.,
       106., 111., 112., 113., 115., 118., 119., 123., 124., 129., 130.,
       133., 137., 139., 144., 145., 149., 154., 156., 161., 162., 163.,
       168., 172., 175., 178., 179., 183., 184., 185., 190., 256.])

In [9]:
length = indptr[1:] - indptr[0:-1] 

## generate length array

In [10]:
length1 = length[0:32]
length2 = length[32:64]
print(len(length1))
print(len(length2))

32
32


In [11]:
f = open("length1.mem", "w")
for i in length1:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

f = open("length2.mem", "w")
for i in length2:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

In [12]:
'{:04x}'.format(64)

'0040'

## generate index array

In [13]:
index1 = index[0:int(indptr[32])]
index2 = index[int(indptr[32]):int(indptr[64])]
print(len(index1))
print(len(index2))

105
151


In [14]:
f = open("index1.mem", "w")
for i in index1:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

f = open("index2.mem", "w")
for i in index2:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

In [15]:
index2

array([52, 42, 44, 39, 50, 12, 15, 28, 22, 33, 61, 53, 58,  4, 32, 49, 53,
        5, 27, 46,  5, 32, 29, 44, 16, 48, 62, 53, 48, 23, 25, 43, 21, 61,
       41, 34, 15, 36, 40,  6, 13, 24, 39, 36, 49, 30, 53, 40, 19, 25, 20,
       50, 47, 50,  0, 32,  7,  6, 44, 19, 17, 20, 33,  1, 59,  8, 14, 43,
       59, 25, 16,  4,  7,  8, 32, 42, 11, 61, 35, 62, 16, 30, 27, 22, 40,
       56, 55, 22, 29, 29, 29, 32, 18, 46,  4, 29, 26, 32, 17, 48, 48, 46,
       45, 53, 22, 24, 59, 50, 40, 55, 23, 29, 50,  3, 46, 37,  8,  0, 62,
       11, 42, 21, 29, 37,  1,  4, 24, 24, 42, 39, 47, 22, 56, 33, 11, 61,
       26, 59, 58, 33, 46, 30, 11, 54,  9, 33, 22, 41, 19, 44, 16])

## generate value array

In [16]:
value1 = value[0:int(indptr[32])]
value2 = value[int(indptr[32]):int(indptr[64])]

In [17]:
f = open("value1.mem", "w")
for i in value1:
    f.write(float32toIEEE754(i))
    f.write("\n")
f.close()

f = open("value2.mem", "w")
for i in value2:
    f.write(float32toIEEE754(i))
    f.write("\n")
f.close()

In [18]:
print(len(value1))
print(len(value2))

105
151


## generate dst array

In [19]:
dst1 = list(range(0,32))
dst2 = list(range(32,64))

In [20]:
f = open("dst1.mem", "w")
for i in dst1:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

f = open("dst2.mem", "w")
for i in dst2:
    f.write('{:04x}'.format(int(i)))
    f.write("\n")
f.close()

In [21]:
dense.size

8192

#  Generate Dense Array

In [22]:
dense.shape

(64, 128)

In [23]:
f = open("dense.mem", "w")
for i in dense:
    for j in i:
        f.write(float32toIEEE754(j))
    f.write("\n")
f.close()

# generate destination result

In [24]:
n = 64
f = 128
result = np.zeros((n,f));
for i in range(0,64):
    for j in range(int(indptr[i]), int(indptr[i + 1])):
        i_value = value[j]
        i_index = index[j]
        for k in range(f):
            result[i,k] =  result[i,k] + i_value * dense[i_index,k]


In [25]:
result

array([[ 1.94591165,  1.29487133,  1.79701574, ...,  1.63901119,
         1.70035338,  1.90444345],
       [ 0.35997971,  0.30425867,  0.62972635, ...,  0.4548212 ,
         0.26064659,  0.07208136],
       [ 2.05936594,  0.97366873,  1.00136796, ...,  2.00006517,
         1.55088154,  2.29993506],
       ...,
       [ 0.14193458,  0.15148802,  0.06030347, ...,  0.03363172,
         0.01643529,  0.05718498],
       [ 2.54027369,  1.41923167,  1.6641643 , ...,  1.24482061,
         1.97564684,  2.62212051],
       [13.10516297, 15.29342422, 13.75077471, ..., 15.59182723,
        10.8285238 , 14.26641889]])

In [30]:
result[31]

array([1.67164253, 1.68575004, 1.62292377, 1.32776031, 0.94210071,
       1.85231792, 1.32655033, 1.59348147, 0.62138823, 0.98548291,
       1.13559049, 0.74995661, 0.90637081, 0.4322395 , 0.9773131 ,
       1.15651248, 1.2117257 , 1.15326304, 0.58839394, 1.43488504,
       1.45885498, 0.70171762, 1.74125045, 1.5220525 , 1.34024428,
       1.64676431, 1.08631999, 1.64328667, 1.00063342, 1.58393461,
       1.03647113, 1.44098866, 1.26309332, 1.04939951, 1.77544331,
       0.43901586, 1.01807217, 1.08620048, 1.0555274 , 1.96538591,
       1.93110229, 1.25802176, 1.90895947, 1.15792567, 0.6310898 ,
       1.57317326, 1.49917031, 1.14436396, 1.04593231, 1.37240055,
       1.21007978, 1.19357099, 1.143105  , 1.20567429, 0.65099134,
       1.37315883, 1.20759481, 1.69772693, 0.73801161, 1.37432695,
       0.60068919, 0.80449414, 1.31203856, 1.80865838, 1.35946771,
       1.97288855, 1.17532174, 1.33519371, 0.92996656, 1.9284219 ,
       1.2551173 , 1.09160191, 1.34294414, 1.06361646, 1.90907

In [27]:
index1

array([50, 32, 41,  8, 28, 25, 23, 43, 51, 52, 52, 55, 36, 38,  2, 19,  2,
       33, 53, 53, 54, 30, 41,  1, 15, 27, 28, 45, 42, 27, 20, 19,  1, 53,
       62,  3, 15, 54, 14, 44,  9, 50, 11, 17,  4, 11, 51, 46, 56,  3, 31,
       28, 16, 59,  2, 49, 10, 58, 53, 61, 29,  6, 36, 48, 51, 27,  5, 43,
       52, 11, 30,  1, 32, 17,  1, 62, 27, 36, 34, 35, 55, 61, 41, 14, 46,
       43, 59, 26, 24,  8, 36, 53, 22, 49,  9, 55, 52, 13, 16, 60, 11, 11,
       57, 56,  7])